import os, re, subprocess, sys, unittest
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
NAMES_FILE = os.path.join(ROOT, "build", "forbidden-names.txt")  # generated by extract_positions.py --names; git-ignored
AGENTS = ["chief-of-staff", "chief-operating-officer", "chief-information-security-officer", "chief-technology-officer",
          "chief-marketing-officer", "chief-sales-officer", "chief-financial-officer"]
USER_SKILLS = ("meet", "setup", "gaps-report")


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return fh.read()


class HygieneTests(unittest.TestCase):
    def tracked(self):
        out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout
        return [l for l in out.splitlines() if l]

    def test_no_workbook_or_remember_tracked(self):
        for f in self.tracked():
            self.assertFalse(f.endswith(".xlsx"), f)
            self.assertFalse(f.startswith(".remember/"), f)
            self.assertNotEqual(f, "org-profile.yaml")

    @unittest.skipUnless(os.path.exists(NAMES_FILE), "build/forbidden-names.txt not generated")
    def test_no_personal_names_in_tracked_text(self):
        with open(NAMES_FILE, encoding="utf-8") as fh:
            tokens = fh.read().split()
        self.assertGreaterEqual(len(tokens), 4)
        # whole words only: a short surname must not match inside words like "transmission"
        names = re.compile(r"\b(?:" + "|".join(map(re.escape, tokens)) + r")\b", re.I)
        self.assertTrue(names.search("x " + tokens[0] + " y"))
        for f in self.tracked():
            if f.endswith((".md", ".json", ".yaml", ".py", ".txt")):
                with open(os.path.join(ROOT, f), encoding="utf-8", errors="ignore") as fh:
                    self.assertIsNone(names.search(fh.read()), f)

    def test_seven_agents_follow_agent_frontmatter_conventions(self):
        for a in AGENTS:
            t = read("agents", a + ".md")
            self.assertTrue(t.startswith("---\nname: " + a + "\n"), a)
            fm = t.split("---")[1]
            self.assertIn("description:", fm)
            self.assertNotIn("tools:", fm)  # Owner decision: officers inherit all tools
            self.assertIn("model: inherit", fm)
            self.assertRegex(fm, r"\ncolor: (blue|cyan|green|yellow|magenta|red)\n")
            self.assertRegex(fm, r'description: Use this agent when .*Typical triggers include .*See "When to invoke"')
            self.assertRegex(t, r"\n## (\d\. )?When to invoke\n")
            self.assertIn("**Do not use", t)

    def test_orchestration_uses_namespaced_agents_and_plugin_root(self):
        cos = read("agents", "chief-of-staff.md")
        meet = read("skills", "meet", "SKILL.md")
        skill = read("skills", "executive-team", "SKILL.md")
        self.assertIn("executive-team:chief-of-staff", meet)
        self.assertIn("${CLAUDE_PLUGIN_ROOT}", meet)
        self.assertIn("executive-team:chief-financial-officer", cos)
        self.assertIn("minutes_dir", cos)
        self.assertIn("Respond in:", cos)
        self.assertIn("Consulted:", skill)
        self.assertIn("## Officer answer format", skill)
        self.assertTrue(skill.splitlines()[2].startswith("description: This skill should be used when"), skill.splitlines()[2])
        for a in AGENTS[1:]:
            self.assertIn("executive-team:executive-team", read("agents", a + ".md"), a)

    def test_user_invoked_skills_replace_legacy_commands(self):
        self.assertFalse(os.path.exists(os.path.join(ROOT, "commands")), "commands/ must be migrated to skills/")
        for s in USER_SKILLS:
            fm = read("skills", s, "SKILL.md").split("---")[1]
            self.assertIn("allowed-tools:", fm, s)
            self.assertIn("description: This skill should be used when", fm, s)
        for gen in ("routing-index.md", "gaps-register.md"):
            self.assertTrue(os.path.exists(os.path.join(ROOT, "skills", "executive-team", "references", gen)), gen)

    @unittest.skipUnless(os.path.exists(os.path.join(ROOT, "build", "workbook-name.txt")), "build/workbook-name.txt not generated")
    def test_workbook_filename_not_in_tracked_text(self):
        with open(os.path.join(ROOT, "build", "workbook-name.txt"), encoding="utf-8") as fh:
            name = fh.read().strip()
        self.assertTrue(name)
        for f in self.tracked():
            if f.endswith((".md", ".json", ".yaml", ".py", ".txt")):
                with open(os.path.join(ROOT, f), encoding="utf-8", errors="ignore") as fh:
                    self.assertNotIn(name, fh.read(), f)

    def test_generated_files_fresh(self):
        r = subprocess.run([sys.executable, "scripts/verify_agents.py", "--check"], cwd=ROOT, capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)


if __name__ == "__main__":
    unittest.main()
