import os, re, subprocess, sys, unittest
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
NAMES_FILE = os.path.join(ROOT, "build", "forbidden-names.txt")  # generated by extract_positions.py --names; git-ignored
AGENTS = ["chief-of-staff", "chief-operating-officer", "chief-information-security-officer", "chief-technology-officer",
          "chief-marketing-officer", "chief-sales-officer", "chief-financial-officer"]


class HygieneTests(unittest.TestCase):
    def tracked(self):
        out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout
        return [l for l in out.splitlines() if l]

    def test_no_workbook_or_remember_tracked(self):
        for f in self.tracked():
            self.assertFalse(f.endswith(".xlsx"), f)
            self.assertFalse(f.startswith(".remember/"), f)
            self.assertNotEqual(f, "org-profile.yaml")

    @unittest.skipUnless(os.path.exists(NAMES_FILE), "build/forbidden-names.txt not generated")
    def test_no_personal_names_in_tracked_text(self):
        tokens = open(NAMES_FILE, encoding="utf-8").read().split()
        self.assertGreaterEqual(len(tokens), 4)
        # whole words only: a short surname must not match inside words like "transmission"
        names = re.compile(r"\b(?:" + "|".join(map(re.escape, tokens)) + r")\b", re.I)
        self.assertTrue(names.search("x " + tokens[0] + " y"))
        for f in self.tracked():
            p = os.path.join(ROOT, f)
            if f.endswith((".md", ".json", ".yaml", ".py", ".txt")):
                self.assertIsNone(names.search(open(p, encoding="utf-8", errors="ignore").read()), f)

    def test_seven_agents_present_with_minimal_frontmatter(self):
        for a in AGENTS:
            t = open(os.path.join(ROOT, "agents", a + ".md"), encoding="utf-8").read()
            self.assertTrue(t.startswith("---\nname: " + a + "\n"), a)
            fm = t.split("---")[1]
            self.assertIn("description:", fm)
            self.assertNotIn("tools:", fm)
            self.assertNotIn("model:", fm)

    def test_generated_files_fresh(self):
        r = subprocess.run([sys.executable, "scripts/verify_agents.py", "--check"], cwd=ROOT, capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)


if __name__ == "__main__":
    unittest.main()
