"""Regenerate the routing index and gaps register from the officer agent files, and check their structure.

Usage:
  python scripts/build_references.py            # check the agent files and rewrite the two reference files
  python scripts/build_references.py --check    # fail if the committed reference files are stale
"""
import glob
import os
import re
import sys
import tempfile

SRC_RE = re.compile(r"^([A-Z]+)!([A-Z]+\d+:[A-Z]+\d+) · FR: (.+)$")
SKILL_RE = re.compile(r"^### Skill (\d+): (.+)$")
FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
LEVEL_VALUES = ("1", "2", "3", "not specified in source")


def _fm(text):
    m = FM_RE.match(text)
    if not m:
        raise ValueError("missing frontmatter")
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    if "name" not in fm or "description" not in fm:
        raise ValueError("frontmatter needs name and description")
    if "tools" in fm:
        raise ValueError("frontmatter must not set tools (officers inherit all tools by Owner decision)")
    if fm.get("model", "inherit") != "inherit":
        raise ValueError("frontmatter model must be 'inherit' or omitted")
    return fm


def parse_officer(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    fm = _fm(text)
    code_m = re.search(r"^# .+\((\w+)\)\s*$", text, re.MULTILINE)
    if not code_m:
        raise ValueError(f"{path}: title line must end with (CODE)")
    o = {
        "path": path, "name": fm["name"], "description": fm["description"],
        "code": code_m.group(1), "skills": [],
        "department_missing": bool(re.search(r"^- Department: not specified in source", text, re.MULTILINE)),
        "manager_missing": bool(re.search(r"^- Position manager: not specified in source", text, re.MULTILINE)),
        "objectives_template": "Status: TEMPLATE" in text,
    }
    obj = re.search(r"Status: TEMPLATE \(source cells (\S+)", text)
    o["objectives_cells"] = obj.group(1) if obj else "?"
    o["missing_columns"] = sorted({m.group(1) for m in re.finditer(r"^- (Description|Associated tasks): column not present in source", text, re.MULTILINE)})
    cur = None
    for line in text.splitlines():
        m = SKILL_RE.match(line)
        if m:
            cur = {"n": int(m.group(1)), "name": m.group(2).strip(), "level": None, "level_raw": None,
                   "sheet": None, "cells": None, "fr": None, "keywords": "", "flags": "none"}
            o["skills"].append(cur)
            continue
        if line.startswith("## "):
            cur = None
            continue
        if cur is None:
            continue
        if line.startswith("- Required level:"):
            v = line.split(":", 1)[1].strip()
            if v not in LEVEL_VALUES:
                raise ValueError(f"{path}: skill {cur['n']} bad level '{v}'")
            cur["level_raw"] = v
            cur["level"] = int(v) if v in ("1", "2", "3") else None
        elif line.startswith("- Source:"):
            sm = SRC_RE.match(line.split(":", 1)[1].strip())
            if not sm:
                raise ValueError(f"{path}: skill {cur['n']} bad Source line")
            cur["sheet"], cur["cells"], cur["fr"] = sm.group(1), sm.group(2), sm.group(3).strip()
        elif line.startswith("- Keywords:"):
            cur["keywords"] = line.split(":", 1)[1].strip()
        elif line.startswith("- Flags:"):
            cur["flags"] = line.split(":", 1)[1].strip()
    return o


def check_structure(o):
    """Return a list of structural problems in one parsed officer (empty when sound)."""
    errs = []
    expected = list(range(1, len(o["skills"]) + 1))
    if [s["n"] for s in o["skills"]] != expected:
        errs.append(f"{o['name']}: skills are not numbered 1..{len(o['skills'])} in order")
    for s in o["skills"]:
        for field in ("level_raw", "cells", "fr"):
            if not s[field]:
                errs.append(f"{o['name']}: skill {s['n']} lacks {field.replace('_raw', '')}")
        if s["sheet"] and s["sheet"] != o["code"]:
            errs.append(f"{o['name']}: skill {s['n']} source sheet {s['sheet']} != officer code {o['code']}")
        if not s["keywords"]:
            errs.append(f"{o['name']}: skill {s['n']} has no keywords")
    return errs


def load_officers(agents_dir):
    files = sorted(glob.glob(os.path.join(agents_dir, "*.md")))
    return [parse_officer(f) for f in files if "chief-of-staff" not in os.path.basename(f)]


def write_index(agents_dir, out_path):
    rows = ["| Officer | Agent | # | Skill | Level | Keywords |", "|---|---|---|---|---|---|"]
    for o in load_officers(agents_dir):
        for s in o["skills"]:
            rows.append(f"| {o['code']} | {o['name']} | {s['n']} | {s['name']} | {s['level'] or 0} | {s['keywords']} |")
    body = ("# Routing index\n\nGenerated by `scripts/build_references.py` from the officer agent files. Do not edit by hand. "
            "Level 0 = not specified in source; use `org-profile.positions.<code>.level_overrides` to set it.\n\n"
            + "\n".join(rows) + "\n")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)


def write_gaps(agents_dir, out_path):
    rows = ["| Officer | Item | Location | Fill with |", "|---|---|---|---|"]
    for o in load_officers(agents_dir):
        c = o["code"]
        lc = c.lower()
        if o["department_missing"]:
            rows.append(f"| {c} | Department | {c} sheet, Department cell | org-profile.positions.{lc}.department |")
        if o["manager_missing"]:
            rows.append(f"| {c} | Position manager | {c} sheet, Position manager cell | org-profile.positions.{lc}.manager |")
        if o["objectives_template"]:
            rows.append(f"| {c} | Strategic objectives (TEMPLATE) | {o['objectives_cells']} | org-profile.strategic_objectives |")
        for col in o["missing_columns"]:
            rows.append(f"| {c} | {col} column | {c} sheet | column not present in source; add it via org-profile.positions.{lc}.extra_skills or leave as is |")
        for s in o["skills"]:
            if s["level"] is None:
                rows.append(f"| {c} | Skill {s['n']} required level | {c}!{s['cells']} | org-profile.positions.{lc}.level_overrides.{s['n']} |")
            if s["flags"] and s["flags"] != "none":
                rows.append(f"| {c} | Skill {s['n']} flag: {s['flags']} | {c}!{s['cells']} | source defect; override via org-profile or leave as is |")
    body = ("# Gaps register\n\nGenerated by `scripts/build_references.py` from the officer agent files. Every field the source "
            "matrix left blank or defective, and the org-profile key that fills it.\n\n" + "\n".join(rows) + "\n")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)


def main(argv):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    agents = os.path.join(root, "agents")
    refs = os.path.join(root, "skills", "executive-team", "references")
    os.makedirs(refs, exist_ok=True)
    errs = []
    for o in load_officers(agents):
        errs.extend(check_structure(o))
    idx = os.path.join(refs, "routing-index.md")
    gaps = os.path.join(refs, "gaps-register.md")
    if "--check" in argv:
        with tempfile.TemporaryDirectory() as d:
            ti, tg = os.path.join(d, "i.md"), os.path.join(d, "g.md")
            write_index(agents, ti)
            write_gaps(agents, tg)
            for a, b, label in ((ti, idx, "routing-index.md"), (tg, gaps, "gaps-register.md")):
                if not os.path.exists(b):
                    errs.append(f"{label} is missing; run scripts/build_references.py")
                    continue
                with open(a, encoding="utf-8") as fa, open(b, encoding="utf-8") as fb:
                    if fa.read() != fb.read():
                        errs.append(f"{label} is stale; run scripts/build_references.py")
    else:
        write_index(agents, idx)
        write_gaps(agents, gaps)
        print(f"wrote {idx}\nwrote {gaps}")
    for e in errs:
        print("ERROR:", e)
    print("OK" if not errs else f"{len(errs)} error(s)")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
